export const USER_ID_CHANGED = 'USER_ID_CHANGED';
export const ALGORITHM_CHANGED = 'ALGORITHM_CHANGED';
export const USER_RECOMMENDATION_ISSUED = 'USER_RECOMMENDATION_ISSUED';
export const USER_ITEMS_ISSUED = 'USER_ITEMS_ISSUED';
